-- MySQL Script generated by MySQL Workbench
-- Tue Nov  2 14:34:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tp_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tp_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tp_integrador` DEFAULT CHARACTER SET utf8 ;
USE `tp_integrador` ;

-- -----------------------------------------------------
-- Table `tp_integrador`.`catalogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`catalogos` (
  `CodigoCatalogo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Fecha_de_baja` DATE NULL,
  PRIMARY KEY (`CodigoCatalogo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp_integrador`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`localidades` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CodigoPostal` VARCHAR(10) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Fecha_de_Baja` DATE NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp_integrador`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`empresas` (
  `Id_Emprendedor` INT NOT NULL AUTO_INCREMENT,
  `TipoEmprendimiento` VARCHAR(100) NOT NULL,
  `Domicilio` VARCHAR(100) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `CodigoCatalogo` INT NOT NULL,
  `Id_Localidades` INT NOT NULL,
  `Fecha_de_baja` DATE NULL,
  PRIMARY KEY (`Id_Emprendedor`),
  INDEX `fk_EMPRENDEDORES_CATALOGOS1_idx` (`CodigoCatalogo` ASC) VISIBLE,
  INDEX `fk_EMPRESAS_LOCALIDADES1_idx` (`Id_Localidades` ASC) VISIBLE,
  CONSTRAINT `fk_EMPRENDEDORES_CATALOGOS1`
    FOREIGN KEY (`CodigoCatalogo`)
    REFERENCES `tp_integrador`.`catalogos` (`CodigoCatalogo`),
  CONSTRAINT `fk_EMPRESAS_LOCALIDADES1`
    FOREIGN KEY (`Id_Localidades`)
    REFERENCES `tp_integrador`.`localidades` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp_integrador`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`roles` (
  `Id_rol` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(10) NOT NULL,
  `Fecha_de_baja` DATE NULL,
  PRIMARY KEY (`Id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp_integrador`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`usuarios` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(20) NOT NULL,
  `Clave` VARCHAR(20) NOT NULL,
  `Fecha_de_baja` DATE NULL,
  PRIMARY KEY (`Id_Usuario`),
  UNIQUE INDEX `nombre_UNIQUE` (`NombreUsuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp_integrador`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`personas` (
  `NroDoc` VARCHAR(10) NOT NULL,
  `TipoDoc` VARCHAR(4) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Telefono` VARCHAR(25) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Id_rol` INT NOT NULL,
  `Id_Empresa` INT NULL DEFAULT NULL,
  `Fecha_de_Baja` DATE NULL,
  `localidades_Id` INT NOT NULL,
  PRIMARY KEY (`NroDoc`),
  INDEX `fk_PERSONAS_USUARIOS1_idx` (`Id_Usuario` ASC) VISIBLE,
  INDEX `fk_PERSONA_ROLES_idx` (`Id_rol` ASC) VISIBLE,
  INDEX `fk_PERSONA_EMPRESA_idx` (`Id_Empresa` ASC) VISIBLE,
  INDEX `fk_personas_localidades1_idx` (`localidades_Id` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONA_EMPRESA`
    FOREIGN KEY (`Id_Empresa`)
    REFERENCES `tp_integrador`.`empresas` (`Id_Emprendedor`),
  CONSTRAINT `fk_PERSONA_ROLES`
    FOREIGN KEY (`Id_rol`)
    REFERENCES `tp_integrador`.`roles` (`Id_rol`),
  CONSTRAINT `fk_PERSONAS_USUARIOS1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `tp_integrador`.`usuarios` (`Id_Usuario`),
  CONSTRAINT `fk_personas_localidades1`
    FOREIGN KEY (`localidades_Id`)
    REFERENCES `tp_integrador`.`localidades` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp_integrador`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`productos` (
  `CodigoProducto` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Precio` DECIMAL(6,2) NOT NULL,
  `Id_Catalogo` INT NOT NULL,
  `Fecha_de_baja` DATE NULL,
  PRIMARY KEY (`CodigoProducto`),
  UNIQUE INDEX `Descripcion_UNIQUE` (`Descripcion` ASC) VISIBLE,
  INDEX `fk_PRODUCTOS_CATALOGOS1_idx` (`Id_Catalogo` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTOS_CATALOGOS1`
    FOREIGN KEY (`Id_Catalogo`)
    REFERENCES `tp_integrador`.`catalogos` (`CodigoCatalogo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp_integrador`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`publicaciones` (
  `Id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(10) NOT NULL,
  `Fecha_de_alta` DATE NOT NULL,
  `Fecha_de_baja` DATE NULL,
  `imagen` VARCHAR(200) NULL,
  `personas_NroDoc` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_publicacion`),
  INDEX `fk_publicaciones_personas1_idx` (`personas_NroDoc` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_personas1`
    FOREIGN KEY (`personas_NroDoc`)
    REFERENCES `tp_integrador`.`personas` (`NroDoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tp_integrador`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tp_integrador`.`comentarios` (
  `Id_comentario` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(10) NOT NULL,
  `Fecha_de_baja` DATE NULL,
  `personas_NroDoc` VARCHAR(10) NOT NULL,
  `publicaciones_Id_publicacion` INT NOT NULL,
  PRIMARY KEY (`Id_comentario`),
  INDEX `fk_comentarios_personas1_idx` (`personas_NroDoc` ASC) VISIBLE,
  INDEX `fk_comentarios_publicaciones1_idx` (`publicaciones_Id_publicacion` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_personas1`
    FOREIGN KEY (`personas_NroDoc`)
    REFERENCES `tp_integrador`.`personas` (`NroDoc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicaciones1`
    FOREIGN KEY (`publicaciones_Id_publicacion`)
    REFERENCES `tp_integrador`.`publicaciones` (`Id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
